### ISSUE TITLE
关于论文两个细节讨论

### ISSUE THREAD

**Issue by jothan706** [NiuTrans/NiuTrans.NMT#4]
你好！
读了你们工程后面附的两篇论文，有两个问题想做一些讨论。
1、2021最优的student model表现甚至高出去年的teacher model，这块主要是做了哪些优化呢？我看到今年teacher model有增加回译，这块的收益是多少？
2、在做en-de序列蒸馏的时候是否需要将训练teacher model，使用的de-en模型输出的回译数据同样用teacher model预测出新结果后给student model学习呢？这块困惑的是如果src序列和tgt序列都来自于机器翻译，在训练的时候会不会是脏数据？

**Comment by huchinlp** [comment]
你好！

1. 我们相对去年主要做了两方面的优化：
  a) 使用了回译和Ensemble优化Teacher模型，回译一轮Teacher模型（Transformer-base）平均涨了1.2个BLEU，但继续迭代回译没有收益。关于回译技术在WMT数据上的效果，你还可以参考我们实验室在2021 WMT News任务上的[评测报告](https://arxiv.org/abs/2109.10485)，里面有比较详细的探究和说明。
  b) 在知识蒸馏的时候引入了Cutoff做数据增强，平均下来也有1个BLEU左右的提升，但受限于计算资源我们只在训Student的时候用了数据增强（训练代价是正常训练的3倍）。具体方法可以参考论文[A Simple but Tough-to-Beat Data Augmentation Approach for Natural Language Understanding and Generation](https://arxiv.org/abs/2009.13818)。

2. 回译的数据只用来训练Teacher模型，训Student模型时源语En使用的是真实的语句，只在目标语De上使用了模型翻译的结果。我们也发现sequence-level的方法比word-level效果更好。具体方法可以参考论文[Sequence-level knowledge distillation](https://arxiv.org/abs/1606.07947)。

**Comment by jothan706** [comment]
谢谢你的回复，想继续了解一下。对于单语回译的数据量有没有要求呢？如果持续增大单语回译数据量能否进一步提升BLEU？

**Comment by areaChun** [comment]
Hi 你好,

我也有用WMT比赛数据跑实验，有拿你论文的结果作为参考对比。在Baseline的结果上，我发现我zh-en\en-zh的结果都跟你在WMT20的上有3 bleu的差距；所以想请教一下。
我的实验设置是：
训练数据：CCMT、UN、WikiMatrix、 News Commentary v15、WikiTitles，清洗后平行语料数据量1600W；
模型：transformer-big;
数据清洗：除了包括你文章提到的规则清洗，还有用翻译结果计算target和predict的bleu值，清除部分中英不对应的数据；

因此，想请教的是：
（1）我的实验baseline结果低原因可能会在哪里，能否提供一些宝贵优化的建议；
（2）请问没有对比Transformer-big和Transformer-dlcl depth=25、Transformer (Pre-Norm) depth=24 的bleu相差有多大，因为我们有用过Transformer-dlcl depth=20，但与Transformer-big结果差不多；当然我设置是lr=0.0005，wamrup=4000，lr设0.001我会出现梯度、loss爆炸；
（3）Xcen的数据选择能否用语言模型替代？

**Comment by libeineu** [comment]
Hi 同学，
我是李北，最近几年WMT比赛参与的比较多，我们团队近几年在WMT上基本都是采用Transformer-DLCL + RPR的设置作为单模型，之后会结合一些模型集成的手段。关于你提到的baseline比较低的问题，首先我想问一下你是用multibleu测试的结果还是WMT比赛官方提交的评价脚本。两个脚本得到的结果是没有太大可比性的。另外你可以提供一下具体的分数，方便对比。比如你跟我们论文报道的分数是同样的设置吗？只使用双语平行数据，未加入back-translation数据？


关于第二点我们做过的实验中DLCL对比big模型会有显著效果提升的，但我们的超参数是lr=0.002 warmup= 16000或8000。本身DLCL会让训练变的稳定一些，所以基本30以内我们没有遇到过loss scale的问题。当然你如果仅仅使用Pre-Norm的深层设置可能在FP16情况遇到loss scale，但这个问题随机性比较大，我们也正在尝试解决。正如我们论文（ACL 2019）提到的，深层网络最好采用大学习率和大batch，也就是说你的batch size也要适当的增大。建议8卡 4096*2 的word batch，如果显卡太小可以考虑使用梯度累计。


关于你提到的Xenc的数据选择，其本身就是基于N-Gram的语言模型，我们也尝试过采用神经网络的语言模型，效果不会显著提升。而且Xenc主要是作为挑选单语数据，可能更适合finetune等场景。如果有其他问题 欢迎讨论。


李北
NiuTrans Team




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NiuTrans/NiuTrans.NMT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月9日(星期四) 中午11:10
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [NiuTrans/NiuTrans.NMT] 关于论文两个细节讨论 (Issue #4)





 
Hi 你好,
 
我也有用WMT比赛数据跑实验，有拿你论文的结果作为参考对比。在Baseline的结果上，我发现我zh-en\en-zh的结果都跟你在WMT20的上有3 bleu的差距；所以想请教一下。
 我的实验设置是：
 训练数据：CCMT、UN、WikiMatrix、 News Commentary v15、WikiTitles，清洗后平行语料数据量1600W；
 模型：transformer-big;
 数据清洗：除了包括你文章提到的规则清洗，还有用翻译结果计算target和predict的bleu值，清除部分中英不对应的数据；
 
因此，想请教的是：
 （1）我的实验baseline结果低原因可能会在哪里，能否提供一些宝贵优化的建议；
 （2）请问没有对比Transformer-big和Transformer-dlcl depth=25、Transformer (Pre-Norm) depth=24 的bleu相差有多大，因为我们有用过Transformer-dlcl depth=20，但与Transformer-big结果差不多；当然我设置是lr=0.0005，wamrup=4000，lr设0.001我会出现梯度、loss爆炸；
 （3）Xcen的数据选择能否用语言模型替代？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by huchinlp** [comment]
> 谢谢你的回复，想继续了解一下。对于单语回译的数据量有没有要求呢？如果持续增大单语回译数据量能否进一步提升BLEU？

根据我们参加WMT的经验，一般单语数据量跟真实双语数据量相同，例如有一千万真实的双语数据，那么第一轮回译就选择一千万单语。我们也尝试过使用更多的单语数据，几乎没有收益。但这些结论跟所选的单语、双语领域和质量都有关系。

**Comment by jothan706** [comment]
使用sequence-level做student model蒸馏训练的时候是否需要将teacher model直译的结果用单语语言模型或者你们论文提到的Xenc工具做一轮清洗呢？直接使用会不会导致student model翻译结果存在漏译的问题

**Comment by areaChun** [comment]
Hi，
感谢李北大神的回复[双手合十]。根据大神题出的疑问，我讲述一下我的实验细节：

1. 对于Bleu，WMT好像用的mteval-v13a.pl计算的，我们则用的sacrebleu计算比较方便。当然，我们也从[Evaluation Matrix](http://matrix.statmt.org/matrix/systems_list/1908)拉了之前比赛结果进行Bleu验证，跟官方的Bleu一致。
2. 我们的Baseline模型 在wmt20上bleu值zh-en:27.3，en-zh:39.3。因为跑的baseline模型，所以没加单边语料回译数据（WMT20体提供的back-translation也没用）。但对比起论文中baseline，en-zh和zh-en差距不小。我们使用数据集和数据清洗方法上面提到，讲初始的2100W数据清洗为1600W。而我们tarnsformer-big训练参数lr=0.0005，warmup=4000；所以，对于提升我的baseline，大神能否给些建议。
3. 对于FP16情况遇到的loss scaler，有没一些缓解的trick。目前，我们跑transformer-big和transformer-dlcl模型，若lr设置大于0.0008，基本必现报错。 TAT
4. 另外，我看了论文中，回译对bleu有4个点提升，比起其他论文提升都很大（看了一下基本在2个点左右）。 除了用了迭代回译，还有其他对回译数据的筛选trick吗？

> Hi 同学， 我是李北，最近几年WMT比赛参与的比较多，我们团队近几年在WMT上基本都是采用Transformer-DLCL + RPR的设置作为单模型，之后会结合一些模型集成的手段。关于你提到的baseline比较低的问题，首先我想问一下你是用multibleu测试的结果还是WMT比赛官方提交的评价脚本。两个脚本得到的结果是没有太大可比性的。另外你可以提供一下具体的分数，方便对比。比如你跟我们论文报道的分数是同样的设置吗？只使用双语平行数据，未加入back-translation数据？ 关于第二点我们做过的实验中DLCL对比big模型会有显著效果提升的，但我们的超参数是lr=0.002 warmup= 16000或8000。本身DLCL会让训练变的稳定一些，所以基本30以内我们没有遇到过loss scale的问题。当然你如果仅仅使用Pre-Norm的深层设置可能在FP16情况遇到loss scale，但这个问题随机性比较大，我们也正在尝试解决。正如我们论文（ACL 2019）提到的，深层网络最好采用大学习率和大batch，也就是说你的batch size也要适当的增大。建议8卡 4096*2 的word batch，如果显卡太小可以考虑使用梯度累计。 关于你提到的Xenc的数据选择，其本身就是基于N-Gram的语言模型，我们也尝试过采用神经网络的语言模型，效果不会显著提升。而且Xenc主要是作为挑选单语数据，可能更适合finetune等场景。如果有其他问题 欢迎讨论。 李北 NiuTrans Team
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "NiuTrans/NiuTrans.NMT" ***@***.***&gt;; 发送时间:&nbsp;2021年12月9日(星期四) 中午11:10 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;Re: [NiuTrans/NiuTrans.NMT] 关于论文两个细节讨论 (Issue #4) Hi 你好, 我也有用WMT比赛数据跑实验，有拿你论文的结果作为参考对比。在Baseline的结果上，我发现我zh-en\en-zh的结果都跟你在WMT20的上有3 bleu的差距；所以想请教一下。 我的实验设置是： 训练数据：CCMT、UN、WikiMatrix、 News Commentary v15、WikiTitles，清洗后平行语料数据量1600W； 模型：transformer-big; 数据清洗：除了包括你文章提到的规则清洗，还有用翻译结果计算target和predict的bleu值，清除部分中英不对应的数据； 因此，想请教的是： （1）我的实验baseline结果低原因可能会在哪里，能否提供一些宝贵优化的建议； （2）请问没有对比Transformer-big和Transformer-dlcl depth=25、Transformer (Pre-Norm) depth=24 的bleu相差有多大，因为我们有用过Transformer-dlcl depth=20，但与Transformer-big结果差不多；当然我设置是lr=0.0005，wamrup=4000，lr设0.001我会出现梯度、loss爆炸； （3）Xcen的数据选择能否用语言模型替代？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by huchinlp** [comment]
> 使用sequence-level做student model蒸馏训练的时候是否需要将teacher model直译的结果用单语语言模型或者你们论文提到的Xenc工具做一轮清洗呢？直接使用会不会导致student model翻译结果存在漏译的问题

用不用语言模型或者Xenc等工具来清洗数据要看具体领域，比如WMT News翻译任务集中在新闻领域，所以可以用工具去筛掉相关性低的数据。但Efficiency任务不对测试数据分布作任何假设，所以我们没有按照领域做数据清洗。漏译的问题我们没有专门去研究，但如果你按照领域分布去清洗后，剩下的都是相关性比较高的数据，一般对模型的负面影响都比较小。

**Comment by libeineu** [comment]
嗨同学，


对于你说的DLCL没法大学习率训练这点我也有点困惑，我这面很多实验都是基于DLCL做的，基本不会出现FP16&nbsp;loss&nbsp;scale的问题。这样，你可以加我微信，libeiiebil，后续有问题我们再讨论。


李北




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月10日(星期五) 上午8:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [NiuTrans/NiuTrans.NMT] 关于论文两个细节讨论 (Issue #4)





 
Hi，
 感谢李北大神的回复[双手合十]。根据大神题出的疑问，我讲述一下我的实验细节：
  
对于Bleu，WMT好像用的mteval-v13a.pl计算的，我们则用的sacrebleu计算比较方便。当然，我们也从Evaluation Matrix拉了之前比赛结果进行Bleu验证，跟官方的Bleu一致。
 
我们的Baseline模型 在wmt20上bleu值zh-en:27.3，en-zh:39.3。因为跑的baseline模型，所以没加单边语料回译数据（WMT20体提供的back-translation也没用）。但对比起论文中baseline，en-zh和zh-en差距不小。我们使用数据集和数据清洗方法上面提到，讲初始的2100W数据清洗为1600W。而我们tarnsformer-big训练参数lr=0.0005，warmup=4000；所以，对于提升我的baseline，大神能否给些建议。
 
对于FP16情况遇到的loss scaler，有没一些缓解的trick。目前，我们跑transformer-big和transformer-dlcl模型，若lr设置大于0.0008，基本必现报错。 TAT
 
另外，我看了论文中，回译对bleu有4个点提升，比起其他论文提升都很大（看了一下基本在2个点左右）。 除了用了迭代回译，还有其他对回译数据的筛选trick吗？
   
Hi 同学， 我是李北，最近几年WMT比赛参与的比较多，我们团队近几年在WMT上基本都是采用Transformer-DLCL + RPR的设置作为单模型，之后会结合一些模型集成的手段。关于你提到的baseline比较低的问题，首先我想问一下你是用multibleu测试的结果还是WMT比赛官方提交的评价脚本。两个脚本得到的结果是没有太大可比性的。另外你可以提供一下具体的分数，方便对比。比如你跟我们论文报道的分数是同样的设置吗？只使用双语平行数据，未加入back-translation数据？ 关于第二点我们做过的实验中DLCL对比big模型会有显著效果提升的，但我们的超参数是lr=0.002 warmup= 16000或8000。本身DLCL会让训练变的稳定一些，所以基本30以内我们没有遇到过loss scale的问题。当然你如果仅仅使用Pre-Norm的深层设置可能在FP16情况遇到loss scale，但这个问题随机性比较大，我们也正在尝试解决。正如我们论文（ACL 2019）提到的，深层网络最好采用大学习率和大batch，也就是说你的batch size也要适当的增大。建议8卡 40962 的word batch，如果显卡太小可以考虑使用梯度累计。 关于你提到的Xenc的数据选择，其本身就是基于N-Gram的语言模型，我们也尝试过采用神经网络的语言模型，效果不会显著提升。而且Xenc主要是作为挑选单语数据，可能更适合finetune等场景。如果有其他问题 欢迎讨论。 李北 NiuTrans Team
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "NiuTrans/NiuTrans.NMT" @.&gt;; 发送时间:&nbsp;2021年12月9日(星期四) 中午11:10 @.&gt;; @.**&gt;; 主题:&nbsp;Re: [NiuTrans/NiuTrans.NMT] 关于论文两个细节讨论 (Issue #4) Hi 你好, 我也有用WMT比赛数据跑实验，有拿你论文的结果作为参考对比。在Baseline的结果上，我发现我zh-en\en-zh的结果都跟你在WMT20的上有3 bleu的差距；所以想请教一下。 我的实验设置是： 训练数据：CCMT、UN、WikiMatrix、 News Commentary v15、WikiTitles，清洗后平行语料数据量1600W； 模型：transformer-big; 数据清洗：除了包括你文章提到的规则清洗，还有用翻译结果计算target和predict的bleu值，清除部分中英不对应的数据； 因此，想请教的是： （1）我的实验baseline结果低原因可能会在哪里，能否提供一些宝贵优化的建议； （2）请问没有对比Transformer-big和Transformer-dlcl depth=25、Transformer (Pre-Norm) depth=24 的bleu相差有多大，因为我们有用过Transformer-dlcl depth=20，但与Transformer-big结果差不多；当然我设置是lr=0.0005，wamrup=4000，lr设0.001我会出现梯度、loss爆炸； （3）Xcen的数据选择能否用语言模型替代？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
